### ISSUE TITLE
Step by step guide?

### ISSUE THREAD

**Issue by caostar** [webextension-toolbox/generator-web-extension#29]
Hello there.
First of all, thank you so much for this tool. 

I am brand new to web extensions development and this is making everything smoother. 
My question is: "shouldn't the YO generator put everything ready to go?"
After I run the YO command,
`npm run dev chrome` gives me errors:

`myApp/node_modules/webextension-toolbox/src/compile.js:7
  const { webpack, ...config } = getConfigFile()
                   ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/beterraba/Documents/Workgit/webextensions/maxmilhas/node_modules/webextension-toolbox/index.js:1:79)
    at Module._compile (module.js:571:32)
`
As I understand, I am missing the webpack.config.js file. But shouldnt YO scaffold that?

Also, a step by step guide on how to quick start with 
webextension-toolbox and webpack-webextension-plugin would be really awesome.

Tks in advance anyway and sorry if I am just missing something dumb! :)

**Comment by caostar** [comment]
Never mind. 
Node was on 
v7.6.0
Npm was on
4.1.2

Updated to
Node 10.10.0
Npm 6.4.1

And compilation went fine.
